version: "3.3"
services:
  redis_db:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "/opt/data/crud-pay-redis:/data"
    restart: on-failure
    command: [ "redis-server", "--appendonly", "yes" ]

  crud-pay:
    container_name: crud-pay-api
    env_file:
      - .env
    depends_on:
      - redis_db
      - mongo_db
    image: crud-pay-api
    ports:
      - "8080:8080"