version: "3.3"
services:
  redis:
    image: redis:latest
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - "${REDIS_CONTAINER_PORT}:6379"
    volumes:
      - "/opt/data/crud-pay-redis:/data"
    restart: on-failure
    command: [ "redis-server", "--appendonly", "yes" ]

  crud-pay:
    container_name: crud-pay-api
    env_file:
      - .env
    depends_on:
      - redis
    links:
      - redis
    image: crud-pay-api
    ports:
      - "8080:8080"